## Using NumPy to perform arithmetic operations on data

In [3]:
import numpy as np
from numpy.random import randn

In [4]:
data = randn(5)
print(data)

[ 1.32615211  0.8322464  -1.38194157 -1.64460476  0.53616326]


In [6]:
np.set_printoptions(precision=2)

In [8]:
data1 = randn(2)
print(data1)

[-0.33 -0.32]


## Creating arrays
### Creating arrays using a list

In [10]:
a = np.array([1,2,3,4,5,6,7])
print(a)
a

[1 2 3 4 5 6 7]


array([1, 2, 3, 4, 5, 6, 7])

In [12]:
b = np.array([[10,20,30],[40,50,60]])
b
print(b)

[[10 20 30]
 [40 50 60]]


### Creating arrays via assignment

In [22]:
np.random.seed(25)
c = 36*np.random.randn(7)
c

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  , -22.32])

In [15]:
d = np.arange(1,35)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

### Multiplying matrices and basic linear algebra

In [19]:
print(a*10)


[10 20 30 40 50 60 70]


In [23]:
c+a

array([  9.22,  38.97, -27.23, -17.28, -29.45,  -2.  , -15.32])